use_frameworks!

target 'Slippers_Example' do
  pod 'Slippers', :path => '../'

  target 'Slippers_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 9.2'
  end
end
