# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlippersStringId' do
  pod 'Slippers/StringId', :path => '..'
  
  target 'SlippersStringIdTests' do
    inherit! :search_paths
  end
end
