# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "11.0.0"

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: cd Example && pod install

      # Build the example app and run tests
      - run:
          name: Build and run tests in Example
          command: cd Example && fastlane scan
          environment:
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: Slippers-Example

#      #Install cocoapods in StringId Example
#      - run:
#          name: Install CocoaPods (StringId)
#          command: cd SlippersStringId && pod install
#      - run:
#          name: Build and run tests in StringIdExample
#          command: cd SlippersStringId && fastlane scan
#          environment:
#            SCAN_DEVICE: iPhone 11
#            SCAN_SCHEME: SlippersStringId

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

